# Configuration for training the texture model
project_directory: "experiments/texture_model"

# Training configuration
model_name: "UNet3D"  # Model type from neurofire.models
model_kwargs:
  in_channels: 1
  out_channels: 1
  final_activation: "Sigmoid"
  depth: 4
  initial_features: 32

# Loss configuration
loss: "MSELoss"
loss_kwargs: {}

# Optimizer configuration
training_optimizer_kwargs:
  optimizer: "Adam"
  optimizer_kwargs:
    lr: 0.0001
    weight_decay: 0.0001

# General training settings
num_epochs: 5
backprop_every: 1
smoothness: 0.95
opt_level: "O1"
mixed_precision: "False"

# Data configuration for contrastive learning
data_config:
  root_dir: "data"
  class_csv_path: "chromatin_classes_and_samples.csv"
  split: 0.2  # 20% of data for validation
  seed: 42

# Contrastive learning settings
contrastive: true
texture_contrastive: false  # Set to true for fine texture model

# Transforms
transforms:
  cast:
    dtype: "float32"
  normalize_range:
    min: 0.0
    max: 1.0
  torch_batch:
    dim: 0

# Transforms for contrastive augmentation
transforms_sim:
  cast:
    dtype: "float32"
  normalize_range:
    min: 0.0
    max: 1.0
  rotate90: true  # Random 90 degree rotations
  torch_batch:
    dim: 0

# Parameters for coarse texture model (RawAEContrCellDataset)
other:
  remove_nucl: false  # Whether to remove nuclei from the image
  only_nucl: false   # Whether to use only nuclei in the image
  dilate_mask: false  # Whether to dilate the mask

# Loader configurations
loader_config:
  batch_size: 8
  shuffle: true
  num_workers: 4
  pin_memory: true

val_loader_config:
  batch_size: 8
  shuffle: false
  num_workers: 4
  pin_memory: true

pred_loader_config:
  batch_size: 1
  shuffle: false
  num_workers: 0
  pin_memory: false 