_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.8.12
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 2
                - 23
                - 55
                - 61
            "4": 3.8.12
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
