# Configuration for training the high-resolution texture model
project_directory: "experiments/highres_texture_model"
device: "cuda"  # Use "cuda" if CUDA is available

# Training configuration
model_name: "UNet3D"  # Model type from neurofire.models
model_kwargs:
  in_channels: 1
  out_channels: 1
  f_maps: [32, 64, 128, 256]
  final_sigmoid: true

# Loss configuration
loss: "BCELoss"
loss_kwargs: {}

# Optimizer configuration
training_optimizer_kwargs:
  optimizer: "Adam"
  optimizer_kwargs:
    lr: 0.0001
    weight_decay: 0.00001

# General training settings
num_epochs: 50
backprop_every: 1
smoothness: 0.95
opt_level: "O1"
mixed_precision: "False"

# Data configuration
data_config:
  root_dir: "nuclei_sample_1a_v1"
  class_csv_path: "chromatin_classes_and_samples.csv"
  is_cytoplasm: false
  box_size: [256, 256, 256]
  split: 0.2
  seed: 42

# Loader configurations
loader_config:
  batch_size: 2
  shuffle: true
  num_workers: 0
  pin_memory: true

val_loader_config:
  batch_size: 2
  shuffle: false
  num_workers: 0
  pin_memory: true 