# Configuration for training the low-resolution texture model
project_directory: experiments/lowres_texture_model
device: "cpu"

# Training configuration
model_name: UNet3D
model_kwargs:
  in_channels: 1
  out_channels: 1
  f_maps: [32, 64, 128, 256]
  final_sigmoid: true

# Loss configuration
loss: BCELoss
loss_kwargs: {}

# Optimizer configuration
training_optimizer_kwargs:
  optimizer: Adam
  optimizer_kwargs:
    lr: 0.0001
    weight_decay: 0.00001

# General training settings
num_epochs: 1
num_epochs_debug: 3  # Fewer epochs for debugging
smoothness: 0.95
opt_level: O1
mixed_precision: 'False'

# Data configuration
data_config:
  # Try using a specific sample directory as root
  root_dir: low_res_dataset
  class_csv_path: chromatin_classes_and_samples.csv  # CSV file with sample information
  is_cytoplasm: false
  box_size: [104, 104, 104]
  split: 0.2  # 20% of data for validation
  seed: 42
  # File format information
  use_tiff: true         # Flag to indicate we're using TIFF files
  input_dir: raw       # Directory containing input TIFF slices
  target_dir: mask     # Directory containing target/mask TIFF slices

# Loader configurations
loader_config:
  batch_size: 2 # Reduced batch size to avoid memory issues with 3D data
  shuffle: true
  num_workers: 0
  pin_memory: true

val_loader_config:
  batch_size: 2  # Reduced batch size to avoid memory issues with 3D data
  shuffle: false
  num_workers: 0
  pin_memory: true

pred_loader_config:
  batch_size: 2
  shuffle: false
  num_workers: 0
  pin_memory: false 