_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.8.12
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 48
                - 53
                - 54
                - 55
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 48
                - 53
                - 54
                - 55
                - 103
            "3":
                - 16
                - 23
                - 55
                - 61
            "4": 3.8.12
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
criterion:
    value:
        kwargs:
            distance:
                function: CosineSimilarity
            neg_margin: 1
            pos_margin: 0
        name: ContrastiveLoss
data:
    value:
        cache_dir: data/mesh_cache
        class_csv_path: chromatin_classes_and_samples.csv
        num_points: 1024
        precomputed_dir: data/mesh_cache
        root_dir: nuclei_sample_1a_v1
device:
    value: cpu
experiment_dir:
    value: results/morphofeatures/shape_model
loader:
    value:
        batch_size: 8
        num_workers: 4
        shuffle: true
model:
    value:
        kwargs:
            act: relu
            channels: 64
            in_channels: 6
            k: 12
            n_blocks: 14
            norm: batch
            out_channels: 64
            projection_head: true
            use_dilation: true
        name: DeepGCN
optimizer:
    value:
        kwargs:
            lr: 0.001
            weight_decay: 0.0001
        name: Adam
output:
    value:
        checkpoint_dir: results/morphofeatures/shape_model/checkpoints
        log_dir: results/morphofeatures/shape_model/logs
        save_every: 5
scheduler:
    value:
        gamma: 0.5
        step_size: 15
training:
    value:
        checkpoint_every: 1
        epochs: 1
        validate_every: 1
use_wandb:
    value: true
wandb_project:
    value: Chromatin
wandb_run_name:
    value: shape_model_training
